volumes:
  wordpress:
    driver: local
    driver_opts:
      type: "bind"
      device: /home/aelbasri/data
      o: "bind"
    name: wordpress

  #database:

services:
  web:
    container_name: my_webserver
    image: nginx_webserver:latest
    ports: 
      - "8080:443"
    build: ./requirements/nginx/
    volumes:
      - wordpress:/var/www/html/

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    build: ./requirements/wordpress/
    volumes:
      - wordpress:/var/www/html/

# db:
