volumes:
  wordpress:
    driver: local
    driver_opts:
      type: "bind"
      device: /home/aelbasri/data/wodpress_files
      o: "bind"
    name: wordpress

  database:
    driver: local
    driver_opts:
        type: "bind"
        device:  /home/aelbasri/data/wodpress_database
        o: "bind"
    name: database

services:
  web:
    container_name: my_webserver
    image: nginx:latest
    ports: 
      - "8080:443"
    build: ./requirements/nginx/
    volumes:
      - wordpress:/var/www/html/

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    build: ./requirements/wordpress/
    env_file: ./.env
    volumes:
      - wordpress:/var/www/html/
  db:
    container_name: mariadb
    image: mariadb:latest
    build: ./requirements/mariadb/
    env_file: ./.env
    volume:
      - database:/var/lib/mysql 

