volumes:
  wordpress:
    driver: local
    driver_opts:
      type: "bind"
      device: /home/aelbasri/data/wordpress_files
      o: "bind"
    name: wordpress

  database:
    driver: local
    driver_opts:
        type: "bind"
        device: /home/aelbasri/data/wordpress_database
        o: "bind"
    name: database

services:
  web:
    container_name: my_webserver
    image: nginx:latest
    ports: 
      - "8080:443"
    build: ./requirements/nginx/
    restart: always
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    build: ./requirements/wordpress/
    env_file: ./.env
    restart: always
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception_network
  db:
    container_name: mariadb
    image: mariadb:latest
    build: ./requirements/mariadb/
    env_file: ./.env
    restart: always
    volumes:
      - database:/var/lib/mysql 
    networks:
      - inception_network

networks:
  inception_network:
