volumes:
  wordpress:
    driver: local
    driver_opts:
      type: "bind"
      device: /home/aelbasri/data/wordpress_files
      o: "bind"
    name: wordpress

  database:
    driver: local
    driver_opts:
        type: "bind"
        device: /home/aelbasri/data/wordpress_database
        o: "bind"
    name: database

services:
  nginx:
    container_name: nginx
    image: nginx:1337
    ports: 
      - "443:443"
    build: ./requirements/nginx/
    env_file: ./.env
    restart: always
    volumes:
      - wordpress:/var/www/html/
    networks:
      - network

  wordpress:
    container_name: wordpress
    image: wordpress:1337
    build: ./requirements/wordpress/
    env_file: ./.env
    restart: always
    volumes:
      - wordpress:/var/www/html/
    networks:
      - network
  mariadb:
    container_name: mariadb
    image: mariadb:1337
    build: ./requirements/mariadb/
    env_file: ./.env
    restart: always
    volumes:
      - database:/var/lib/mysql 
    networks:
      - network

  redis:
    container_name: redis
    image: redis:1337
    build: ./requirements/bonus/redis
    env_file: ./.env
    restart: always
    networks:
      - network
networks:
  network:
    driver: bridge
