#! /bin/bash

echo HELOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO1
#mariadbd-safe
echo HELOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2

mariadb

echo CREATE DATABASE "$DBNAME";
echo CREATE USER "$DBUSER"@'localhost' IDENTIFIED BY "$DBPASS";
echo GRANT ALL PRIVILEGES ON wordpress.* TO "$DBUSER"@'localhost';
echo FLUSH PRIVILEGES;
echo EXIT;

